version: 1
descriptor_core_version: 1
descriptors {
  id: "tensorflow_extension"
  version: 1
}
graphs {
  id: "main"
  nodes {
    id: "v_output"
    inputs: "Reshape"
    operation: "Activation"
    fields {
      key: "func"
      value {
        s: "sigmoid"
      }
    }
  }
  nodes {
    id: "Reshape"
    inputs: "Relu_9"
    inputs: "Reshape/shape"
    operation: "Reshape"
  }
  nodes {
    id: "Reshape/shape"
    operation: "Const"
    fields {
      key: "dtype"
      value {
        dtype: DT_INT32
      }
    }
    fields {
      key: "shape"
      value {
        i_list {
          val: 2
        }
      }
    }
    fields {
      key: "values"
      value {
        ref: "weights_Reshape/shape"
      }
    }
  }
  nodes {
    id: "Relu_9"
    inputs: "Conv2D_9"
    operation: "Activation"
    fields {
      key: "func"
      value {
        s: "relu"
      }
    }
  }
  nodes {
    id: "Conv2D_9"
    inputs: "Relu_8"
    inputs: "cW1"
    operation: "Conv"
    fields {
      key: "implicit_padding"
      value {
        s: "same"
      }
    }
    fields {
      key: "inputs_orders"
      value {
        ref: "orders_NC+_+CK"
      }
    }
    fields {
      key: "strides"
      value {
        i_list {
          val: 1
          val: 1
        }
      }
    }
  }
  nodes {
    id: "cW1"
    operation: "Const"
    fields {
      key: "dtype"
      value {
        dtype: DT_FLOAT32
      }
    }
    fields {
      key: "shape"
      value {
        i_list {
          val: 3
          val: 3
          val: 32
          val: 4
        }
      }
    }
    fields {
      key: "values"
      value {
        ref: "weights_cW1"
      }
    }
  }
  nodes {
    id: "Relu_8"
    inputs: "add_3"
    operation: "Activation"
    fields {
      key: "func"
      value {
        s: "relu"
      }
    }
  }
  nodes {
    id: "add_3"
    inputs: "Conv2D_8"
    inputs: "Relu_6"
    operation: "Binary"
    fields {
      key: "func"
      value {
        s: "add"
      }
    }
  }
  nodes {
    id: "Relu_6"
    inputs: "add_2"
    operation: "Activation"
    fields {
      key: "func"
      value {
        s: "relu"
      }
    }
  }
  nodes {
    id: "add_2"
    inputs: "Conv2D_6"
    inputs: "Relu_4"
    operation: "Binary"
    fields {
      key: "func"
      value {
        s: "add"
      }
    }
  }
  nodes {
    id: "Relu_4"
    inputs: "add_1"
    operation: "Activation"
    fields {
      key: "func"
      value {
        s: "relu"
      }
    }
  }
  nodes {
    id: "add_1"
    inputs: "Conv2D_4"
    inputs: "Relu_2"
    operation: "Binary"
    fields {
      key: "func"
      value {
        s: "add"
      }
    }
  }
  nodes {
    id: "Relu_2"
    inputs: "add"
    operation: "Activation"
    fields {
      key: "func"
      value {
        s: "relu"
      }
    }
  }
  nodes {
    id: "add"
    inputs: "Conv2D_2"
    inputs: "Relu"
    operation: "Binary"
    fields {
      key: "func"
      value {
        s: "add"
      }
    }
  }
  nodes {
    id: "Relu"
    inputs: "Conv2D"
    operation: "Activation"
    fields {
      key: "func"
      value {
        s: "relu"
      }
    }
  }
  nodes {
    id: "Conv2D"
    inputs: "input_node"
    inputs: "cW0"
    operation: "Conv"
    fields {
      key: "implicit_padding"
      value {
        s: "same"
      }
    }
    fields {
      key: "inputs_orders"
      value {
        ref: "orders_NC+_+CK"
      }
    }
    fields {
      key: "strides"
      value {
        i_list {
          val: 1
          val: 1
        }
      }
    }
  }
  nodes {
    id: "cW0"
    operation: "Const"
    fields {
      key: "dtype"
      value {
        dtype: DT_FLOAT32
      }
    }
    fields {
      key: "shape"
      value {
        i_list {
          val: 3
          val: 3
          val: 10
          val: 32
        }
      }
    }
    fields {
      key: "values"
      value {
        ref: "weights_cW0"
      }
    }
  }
  nodes {
    id: "input_node"
    operation: "Input"
    fields {
      key: "dtype"
      value {
        dtype: DT_FLOAT32
      }
    }
    fields {
      key: "shape"
      value {
        i_list {
          val: -1
          val: 10
          val: 9
          val: 9
        }
      }
    }
  }
  nodes {
    id: "Conv2D_2"
    inputs: "Relu_1"
    inputs: "rWB1"
    operation: "Conv"
    fields {
      key: "implicit_padding"
      value {
        s: "same"
      }
    }
    fields {
      key: "inputs_orders"
      value {
        ref: "orders_NC+_+CK"
      }
    }
    fields {
      key: "strides"
      value {
        i_list {
          val: 1
          val: 1
        }
      }
    }
  }
  nodes {
    id: "rWB1"
    operation: "Const"
    fields {
      key: "dtype"
      value {
        dtype: DT_FLOAT32
      }
    }
    fields {
      key: "shape"
      value {
        i_list {
          val: 3
          val: 3
          val: 32
          val: 32
        }
      }
    }
    fields {
      key: "values"
      value {
        ref: "weights_rWB1"
      }
    }
  }
  nodes {
    id: "Relu_1"
    inputs: "Conv2D_1"
    operation: "Activation"
    fields {
      key: "func"
      value {
        s: "relu"
      }
    }
  }
  nodes {
    id: "Conv2D_1"
    inputs: "Relu"
    inputs: "rWA1"
    operation: "Conv"
    fields {
      key: "implicit_padding"
      value {
        s: "same"
      }
    }
    fields {
      key: "inputs_orders"
      value {
        ref: "orders_NC+_+CK"
      }
    }
    fields {
      key: "strides"
      value {
        i_list {
          val: 1
          val: 1
        }
      }
    }
  }
  nodes {
    id: "rWA1"
    operation: "Const"
    fields {
      key: "dtype"
      value {
        dtype: DT_FLOAT32
      }
    }
    fields {
      key: "shape"
      value {
        i_list {
          val: 3
          val: 3
          val: 32
          val: 32
        }
      }
    }
    fields {
      key: "values"
      value {
        ref: "weights_rWA1"
      }
    }
  }
  nodes {
    id: "Conv2D_4"
    inputs: "Relu_3"
    inputs: "rWB2"
    operation: "Conv"
    fields {
      key: "implicit_padding"
      value {
        s: "same"
      }
    }
    fields {
      key: "inputs_orders"
      value {
        ref: "orders_NC+_+CK"
      }
    }
    fields {
      key: "strides"
      value {
        i_list {
          val: 1
          val: 1
        }
      }
    }
  }
  nodes {
    id: "rWB2"
    operation: "Const"
    fields {
      key: "dtype"
      value {
        dtype: DT_FLOAT32
      }
    }
    fields {
      key: "shape"
      value {
        i_list {
          val: 3
          val: 3
          val: 32
          val: 32
        }
      }
    }
    fields {
      key: "values"
      value {
        ref: "weights_rWB2"
      }
    }
  }
  nodes {
    id: "Relu_3"
    inputs: "Conv2D_3"
    operation: "Activation"
    fields {
      key: "func"
      value {
        s: "relu"
      }
    }
  }
  nodes {
    id: "Conv2D_3"
    inputs: "Relu_2"
    inputs: "rWA2"
    operation: "Conv"
    fields {
      key: "implicit_padding"
      value {
        s: "same"
      }
    }
    fields {
      key: "inputs_orders"
      value {
        ref: "orders_NC+_+CK"
      }
    }
    fields {
      key: "strides"
      value {
        i_list {
          val: 1
          val: 1
        }
      }
    }
  }
  nodes {
    id: "rWA2"
    operation: "Const"
    fields {
      key: "dtype"
      value {
        dtype: DT_FLOAT32
      }
    }
    fields {
      key: "shape"
      value {
        i_list {
          val: 3
          val: 3
          val: 32
          val: 32
        }
      }
    }
    fields {
      key: "values"
      value {
        ref: "weights_rWA2"
      }
    }
  }
  nodes {
    id: "Conv2D_6"
    inputs: "Relu_5"
    inputs: "rWB3"
    operation: "Conv"
    fields {
      key: "implicit_padding"
      value {
        s: "same"
      }
    }
    fields {
      key: "inputs_orders"
      value {
        ref: "orders_NC+_+CK"
      }
    }
    fields {
      key: "strides"
      value {
        i_list {
          val: 1
          val: 1
        }
      }
    }
  }
  nodes {
    id: "rWB3"
    operation: "Const"
    fields {
      key: "dtype"
      value {
        dtype: DT_FLOAT32
      }
    }
    fields {
      key: "shape"
      value {
        i_list {
          val: 3
          val: 3
          val: 32
          val: 32
        }
      }
    }
    fields {
      key: "values"
      value {
        ref: "weights_rWB3"
      }
    }
  }
  nodes {
    id: "Relu_5"
    inputs: "Conv2D_5"
    operation: "Activation"
    fields {
      key: "func"
      value {
        s: "relu"
      }
    }
  }
  nodes {
    id: "Conv2D_5"
    inputs: "Relu_4"
    inputs: "rWA3"
    operation: "Conv"
    fields {
      key: "implicit_padding"
      value {
        s: "same"
      }
    }
    fields {
      key: "inputs_orders"
      value {
        ref: "orders_NC+_+CK"
      }
    }
    fields {
      key: "strides"
      value {
        i_list {
          val: 1
          val: 1
        }
      }
    }
  }
  nodes {
    id: "rWA3"
    operation: "Const"
    fields {
      key: "dtype"
      value {
        dtype: DT_FLOAT32
      }
    }
    fields {
      key: "shape"
      value {
        i_list {
          val: 3
          val: 3
          val: 32
          val: 32
        }
      }
    }
    fields {
      key: "values"
      value {
        ref: "weights_rWA3"
      }
    }
  }
  nodes {
    id: "Conv2D_8"
    inputs: "Relu_7"
    inputs: "rWB4"
    operation: "Conv"
    fields {
      key: "implicit_padding"
      value {
        s: "same"
      }
    }
    fields {
      key: "inputs_orders"
      value {
        ref: "orders_NC+_+CK"
      }
    }
    fields {
      key: "strides"
      value {
        i_list {
          val: 1
          val: 1
        }
      }
    }
  }
  nodes {
    id: "rWB4"
    operation: "Const"
    fields {
      key: "dtype"
      value {
        dtype: DT_FLOAT32
      }
    }
    fields {
      key: "shape"
      value {
        i_list {
          val: 3
          val: 3
          val: 32
          val: 32
        }
      }
    }
    fields {
      key: "values"
      value {
        ref: "weights_rWB4"
      }
    }
  }
  nodes {
    id: "Relu_7"
    inputs: "Conv2D_7"
    operation: "Activation"
    fields {
      key: "func"
      value {
        s: "relu"
      }
    }
  }
  nodes {
    id: "Conv2D_7"
    inputs: "Relu_6"
    inputs: "rWA4"
    operation: "Conv"
    fields {
      key: "implicit_padding"
      value {
        s: "same"
      }
    }
    fields {
      key: "inputs_orders"
      value {
        ref: "orders_NC+_+CK"
      }
    }
    fields {
      key: "strides"
      value {
        i_list {
          val: 1
          val: 1
        }
      }
    }
  }
  nodes {
    id: "rWA4"
    operation: "Const"
    fields {
      key: "dtype"
      value {
        dtype: DT_FLOAT32
      }
    }
    fields {
      key: "shape"
      value {
        i_list {
          val: 3
          val: 3
          val: 32
          val: 32
        }
      }
    }
    fields {
      key: "values"
      value {
        ref: "weights_rWA4"
      }
    }
  }
  nodes {
    id: "MarkOutput_0"
    inputs: "v_output"
    operation: "MarkOutput"
  }
}
referenced_data {
  key: "orders_NC+_+CK"
  value {
    dim_orders_list {
      val {
        orders {
          key: -1
          value {
            val: 0
            val: 1
            val: 2
            val: 2147483647
          }
        }
      }
      val {
        orders {
          key: -1
          value {
            val: 2
            val: 2147483647
            val: 1
            val: 0
          }
        }
      }
    }
  }
}
referenced_data {
  key: "weights_Reshape/shape"
  value {
    blob: "\377\377\377\377D\001\000\000"
  }
}
referenced_data {
  key: "weights_cW0"
  value {
    blob: "(...11520 bytes skipped...)"
  }
}
referenced_data {
  key: "weights_cW1"
  value {
    blob: "(...4608 bytes skipped...)"
  }
}
referenced_data {
  key: "weights_rWA1"
  value {
    blob: "(...36864 bytes skipped...)"
  }
}
referenced_data {
  key: "weights_rWA2"
  value {
    blob: "(...36864 bytes skipped...)"
  }
}
referenced_data {
  key: "weights_rWA3"
  value {
    blob: "(...36864 bytes skipped...)"
  }
}
referenced_data {
  key: "weights_rWA4"
  value {
    blob: "(...36864 bytes skipped...)"
  }
}
referenced_data {
  key: "weights_rWB1"
  value {
    blob: "(...36864 bytes skipped...)"
  }
}
referenced_data {
  key: "weights_rWB2"
  value {
    blob: "(...36864 bytes skipped...)"
  }
}
referenced_data {
  key: "weights_rWB3"
  value {
    blob: "(...36864 bytes skipped...)"
  }
}
referenced_data {
  key: "weights_rWB4"
  value {
    blob: "(...36864 bytes skipped...)"
  }
}
